<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\FeeChallan;

class ChallanTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        FeeChallan::create([
            'id' => 1,
            'Name' => 'AYESHA NOREEN',
            'fatherName' => 'Shahid Mehmood',
            'CNIC' => '36300-0000000-1',
            'Roll_No' =>'CPE-23-01',
            'Reg_No' => '1',
            'Session' =>'2023-2027',
            
            'Admission_Challan_Draft' => Null,
            'Admission_Challan_Paid' => Null,
            'Semester_1_Draft' => Null,
            'Semester_1_Paid' => Null,
            'Semester_2_Draft' => Null,
            'Semester_2_Paid' => Null,
            'Semester_3_Draft' => Null,
            'Semester_3_Paid' => Null,
            'Semester_4_Draft' => Null,
            'Semester_4_Paid' => Null,
            'Semester_5_Draft' => Null,
            'Semester_5_Paid' => Null,
            'Semester_6_Draft' => Null,
            'Semester_6_Paid' => Null,
            'Semester_7_Draft' => Null,
            'Semester_7_Paid' => Null,
            'Semester_8_Draft' => Null,
            'Semester_8_Paid' => Null,

        ]);

        FeeChallan::create([
            'id' => 2,
            'Name' => 'MUHAMMAD RAZA',
            'fatherName' => ' ',
            'CNIC' => '36300-0000000-2',
            'Roll_No' => 'CPE-23-02',
            'Reg_No' => '2',
            'Session' =>  '2023-2027',
               
            'Admission_Challan_Draft' => Null,
            'Admission_Challan_Paid' => Null,
            'Semester_1_Draft' => Null,
            'Semester_1_Paid' => Null,
            'Semester_2_Draft' => Null,
            'Semester_2_Paid' => Null,
            'Semester_3_Draft' => Null,
            'Semester_3_Paid' => Null,
            'Semester_4_Draft' => Null,
            'Semester_4_Paid' => Null,
            'Semester_5_Draft' => Null,
            'Semester_5_Paid' => Null,
            'Semester_6_Draft' => Null,
            'Semester_6_Paid' => Null,
            'Semester_7_Draft' => Null,
            'Semester_7_Paid' => Null,
            'Semester_8_Draft' => Null,
            'Semester_8_Paid' => Null,
        ]);

        FeeChallan::create([
            'id' => 3,
            'Name' => 'ANIQA IMRAN',
            'fatherName' => ' ',
            'CNIC' => '36300-0000000-3',
            'Roll_No' => 'CPE-23-03',
            'Reg_No' => '3',
            'Session' =>  '2023-2027',
              
            'Admission_Challan_Draft' => Null,
            'Admission_Challan_Paid' => Null,
            'Semester_1_Draft' => Null,
            'Semester_1_Paid' => Null,
            'Semester_2_Draft' => Null,
            'Semester_2_Paid' => Null,
            'Semester_3_Draft' => Null,
            'Semester_3_Paid' => Null,
            'Semester_4_Draft' => Null,
            'Semester_4_Paid' => Null,
            'Semester_5_Draft' => Null,
            'Semester_5_Paid' => Null,
            'Semester_6_Draft' => Null,
            'Semester_6_Paid' => Null,
            'Semester_7_Draft' => Null,
            'Semester_7_Paid' => Null,
            'Semester_8_Draft' => Null,
            'Semester_8_Paid' => Null,
        ]);

        FeeChallan::create([
            'id' => 4,
            'Name' => 'UQAAB HAIDER',
            'fatherName' => ' ',
            'CNIC' => '36300-0000000-4',
            'Roll_No' => 'CPE-23-04',
            'Reg_No' => '4',
            'Session' =>  '2023-2027',
            
 
            'Admission_Challan_Draft' => Null,
            'Admission_Challan_Paid' => Null,
            'Semester_1_Draft' => Null,
            'Semester_1_Paid' => Null,
            'Semester_2_Draft' => Null,
            'Semester_2_Paid' => Null,
            'Semester_3_Draft' => Null,
            'Semester_3_Paid' => Null,
            'Semester_4_Draft' => Null,
            'Semester_4_Paid' => Null,
            'Semester_5_Draft' => Null,
            'Semester_5_Paid' => Null,
            'Semester_6_Draft' => Null,
            'Semester_6_Paid' => Null,
            'Semester_7_Draft' => Null,
            'Semester_7_Paid' => Null,
            'Semester_8_Draft' => Null,
            'Semester_8_Paid' => Null,
        ]);

        FeeChallan::create([
            'id' => 5,
            'Name' => 'BUSHRA KANOOZ KHAN',
            'fatherName' => ' ',
            'CNIC' => '36300-0000000-5',
            'Roll_No' => 'CPE-23-05',
            'Reg_No' => '5',
            'Session' =>  '2023-2027',
             
            'Admission_Challan_Draft' => Null,
            'Admission_Challan_Paid' => Null,
            'Semester_1_Draft' => Null,
            'Semester_1_Paid' => Null,
            'Semester_2_Draft' => Null,
            'Semester_2_Paid' => Null,
            'Semester_3_Draft' => Null,
            'Semester_3_Paid' => Null,
            'Semester_4_Draft' => Null,
            'Semester_4_Paid' => Null,
            'Semester_5_Draft' => Null,
            'Semester_5_Paid' => Null,
            'Semester_6_Draft' => Null,
            'Semester_6_Paid' => Null,
            'Semester_7_Draft' => Null,
            'Semester_7_Paid' => Null,
            'Semester_8_Draft' => Null,
            'Semester_8_Paid' => Null,
        ]);

        FeeChallan::create([
            'id' => 6,
            'Name' => 'MUHAMMAD RIZWAN',
            'fatherName' => ' ',
            'CNIC' => '36300-0000000-6',
            'Roll_No' => 'CPE-23-06',
            'Reg_No' => '6',
            'Session' =>  '2023-2027',
              
            'Admission_Challan_Draft' => Null,
            'Admission_Challan_Paid' => Null,
            'Semester_1_Draft' => Null,
            'Semester_1_Paid' => Null,
            'Semester_2_Draft' => Null,
            'Semester_2_Paid' => Null,
            'Semester_3_Draft' => Null,
            'Semester_3_Paid' => Null,
            'Semester_4_Draft' => Null,
            'Semester_4_Paid' => Null,
            'Semester_5_Draft' => Null,
            'Semester_5_Paid' => Null,
            'Semester_6_Draft' => Null,
            'Semester_6_Paid' => Null,
            'Semester_7_Draft' => Null,
            'Semester_7_Paid' => Null,
            'Semester_8_Draft' => Null,
            'Semester_8_Paid' => Null,
        ]);

        FeeChallan::create([
            'id' => 7,
            'Name' => 'ALEENA KHAN',
            'fatherName' => ' ',
            'CNIC' => '36300-0000000-7',
            'Roll_No' => 'CPE-23-08',
            'Reg_No' => '7',
            'Session' =>  '2023-2027',
            

            'Admission_Challan_Draft' => Null,
            'Admission_Challan_Paid' => Null,
            'Semester_1_Draft' => Null,
            'Semester_1_Paid' => Null,
            'Semester_2_Draft' => Null,
            'Semester_2_Paid' => Null,
            'Semester_3_Draft' => Null,
            'Semester_3_Paid' => Null,
            'Semester_4_Draft' => Null,
            'Semester_4_Paid' => Null,
            'Semester_5_Draft' => Null,
            'Semester_5_Paid' => Null,
            'Semester_6_Draft' => Null,
            'Semester_6_Paid' => Null,
            'Semester_7_Draft' => Null,
            'Semester_7_Paid' => Null,
            'Semester_8_Draft' => Null,
            'Semester_8_Paid' => Null,
        ]);

        FeeChallan::create([
            'id' => 8,
            'Name' => 'EISHA ARAIN',
            'fatherName' => ' ',
            'CNIC' => '36300-0000000-8',
            'Roll_No' => 'CPE-23-09',
            'Reg_No' => '8',
            'Session' =>  '2023-2027',
           'Admission_Challan_Draft' => Null,
            'Admission_Challan_Paid' => Null,
            'Semester_1_Draft' => Null,
            'Semester_1_Paid' => Null,
            'Semester_2_Draft' => Null,
            'Semester_2_Paid' => Null,
            'Semester_3_Draft' => Null,
            'Semester_3_Paid' => Null,
            'Semester_4_Draft' => Null,
            'Semester_4_Paid' => Null,
            'Semester_5_Draft' => Null,
            'Semester_5_Paid' => Null,
            'Semester_6_Draft' => Null,
            'Semester_6_Paid' => Null,
            'Semester_7_Draft' => Null,
            'Semester_7_Paid' => Null,
            'Semester_8_Draft' => Null,
            'Semester_8_Paid' => Null,
        ]);

        FeeChallan::create([
            'id' => 9,
            'Name' => 'FAHAD USMAN',
            'fatherName' => ' ',
            'CNIC' => '36300-0000000-9',
            'Roll_No' => 'CPE-23-10',
            'Reg_No' => '9',
            'Session' =>  '2023-2027',
            
      'Admission_Challan_Draft' => Null,
            'Admission_Challan_Paid' => Null,
            'Semester_1_Draft' => Null,
            'Semester_1_Paid' => Null,
            'Semester_2_Draft' => Null,
            'Semester_2_Paid' => Null,
            'Semester_3_Draft' => Null,
            'Semester_3_Paid' => Null,
            'Semester_4_Draft' => Null,
            'Semester_4_Paid' => Null,
            'Semester_5_Draft' => Null,
            'Semester_5_Paid' => Null,
            'Semester_6_Draft' => Null,
            'Semester_6_Paid' => Null,
            'Semester_7_Draft' => Null,
            'Semester_7_Paid' => Null,
            'Semester_8_Draft' => Null,
            'Semester_8_Paid' => Null,
        ]);

        FeeChallan::create([
            'id' => 10,
            'Name' => 'MUHAMMAD MEHDI',
            'fatherName' => ' ',
            'CNIC' => '36300-0000000-10',
            'Roll_No' => 'CPE-23-11',
            'Reg_No' => '10',
            'Session' =>  '2023-2027',
            
       
            'Admission_Challan_Draft' => Null,
            'Admission_Challan_Paid' => Null,
            'Semester_1_Draft' => Null,
            'Semester_1_Paid' => Null,
            'Semester_2_Draft' => Null,
            'Semester_2_Paid' => Null,
            'Semester_3_Draft' => Null,
            'Semester_3_Paid' => Null,
            'Semester_4_Draft' => Null,
            'Semester_4_Paid' => Null,
            'Semester_5_Draft' => Null,
            'Semester_5_Paid' => Null,
            'Semester_6_Draft' => Null,
            'Semester_6_Paid' => Null,
            'Semester_7_Draft' => Null,
            'Semester_7_Paid' => Null,
            'Semester_8_Draft' => Null,
            'Semester_8_Paid' => Null,
        ]);

        FeeChallan::create([
            'id' => 11,
            'Name' => 'MUHAMMAD UMER',
            'fatherName' => ' ',
            'CNIC' => '36300-0000000-11',
            'Roll_No' => 'CPE-23-12',
            'Reg_No' => '11',
            'Session' =>  '2023-2027',
            
            'Admission_Challan_Draft' => Null,
            'Admission_Challan_Paid' => Null,
            'Semester_1_Draft' => Null,
            'Semester_1_Paid' => Null,
            'Semester_2_Draft' => Null,
            'Semester_2_Paid' => Null,
            'Semester_3_Draft' => Null,
            'Semester_3_Paid' => Null,
            'Semester_4_Draft' => Null,
            'Semester_4_Paid' => Null,
            'Semester_5_Draft' => Null,
            'Semester_5_Paid' => Null,
            'Semester_6_Draft' => Null,
            'Semester_6_Paid' => Null,
            'Semester_7_Draft' => Null,
            'Semester_7_Paid' => Null,
            'Semester_8_Draft' => Null,
            'Semester_8_Paid' => Null,
        ]);

        FeeChallan::create([
            'id' => 12,
            'Name' => 'MUHAMMAD ALI',
            'fatherName' => ' ',
            'CNIC' => '36300-0000000-12',
            'Roll_No' => 'CPE-23-13',
            'Reg_No' => '12',
            'Session' =>  '2023-2027',
              'Admission_Challan_Draft' => Null,
            'Admission_Challan_Paid' => Null,
            'Semester_1_Draft' => Null,
            'Semester_1_Paid' => Null,
            'Semester_2_Draft' => Null,
            'Semester_2_Paid' => Null,
            'Semester_3_Draft' => Null,
            'Semester_3_Paid' => Null,
            'Semester_4_Draft' => Null,
            'Semester_4_Paid' => Null,
            'Semester_5_Draft' => Null,
            'Semester_5_Paid' => Null,
            'Semester_6_Draft' => Null,
            'Semester_6_Paid' => Null,
            'Semester_7_Draft' => Null,
            'Semester_7_Paid' => Null,
            'Semester_8_Draft' => Null,
            'Semester_8_Paid' => Null,
        ]);

        FeeChallan::create([
            'id' => 13,
            'Name' => 'ALIZA NOREEN',
            'fatherName' => ' ',
            'CNIC' => '36300-0000000-13',
            'Roll_No' => 'CPE-23-14',
            'Reg_No' => '13',
            'Session' =>  '2023-2027',
            
       'Admission_Challan_Draft' => Null,
            'Admission_Challan_Paid' => Null,
            'Semester_1_Draft' => Null,
            'Semester_1_Paid' => Null,
            'Semester_2_Draft' => Null,
            'Semester_2_Paid' => Null,
            'Semester_3_Draft' => Null,
            'Semester_3_Paid' => Null,
            'Semester_4_Draft' => Null,
            'Semester_4_Paid' => Null,
            'Semester_5_Draft' => Null,
            'Semester_5_Paid' => Null,
            'Semester_6_Draft' => Null,
            'Semester_6_Paid' => Null,
            'Semester_7_Draft' => Null,
            'Semester_7_Paid' => Null,
            'Semester_8_Draft' => Null,
            'Semester_8_Paid' => Null,
        ]);

        FeeChallan::create([
            'id' => 14,
            'Name' => 'ALI SACHAL ABDULLAH',
            'fatherName' => ' ',
            'CNIC' => '36300-0000000-14',
            'Roll_No' => 'CPE-23-15',
            'Reg_No' => '14',
            'Session' =>  '2023-2027',
               
            'Admission_Challan_Draft' => Null,
            'Admission_Challan_Paid' => Null,
            'Semester_1_Draft' => Null,
            'Semester_1_Paid' => Null,
            'Semester_2_Draft' => Null,
            'Semester_2_Paid' => Null,
            'Semester_3_Draft' => Null,
            'Semester_3_Paid' => Null,
            'Semester_4_Draft' => Null,
            'Semester_4_Paid' => Null,
            'Semester_5_Draft' => Null,
            'Semester_5_Paid' => Null,
            'Semester_6_Draft' => Null,
            'Semester_6_Paid' => Null,
            'Semester_7_Draft' => Null,
            'Semester_7_Paid' => Null,
            'Semester_8_Draft' => Null,
            'Semester_8_Paid' => Null,
        ]);

        FeeChallan::create([
            'id' => 15,
            'Name' => 'AQIB HUSSAIN',
            'fatherName' => ' ',
            'CNIC' => '36300-0000000-15',
            'Roll_No' => 'CPE-23-16',
            'Reg_No' => '15',
            'Session' =>  '2023-2027',
            
            'Admission_Challan_Draft' => Null,
            'Admission_Challan_Paid' => Null,
            'Semester_1_Draft' => Null,
            'Semester_1_Paid' => Null,
            'Semester_2_Draft' => Null,
            'Semester_2_Paid' => Null,
            'Semester_3_Draft' => Null,
            'Semester_3_Paid' => Null,
            'Semester_4_Draft' => Null,
            'Semester_4_Paid' => Null,
            'Semester_5_Draft' => Null,
            'Semester_5_Paid' => Null,
            'Semester_6_Draft' => Null,
            'Semester_6_Paid' => Null,
            'Semester_7_Draft' => Null,
            'Semester_7_Paid' => Null,
            'Semester_8_Draft' => Null,
            'Semester_8_Paid' => Null,
        ]);

        FeeChallan::create([
            'id' => 16,
            'Name' => 'MUHAMMAD SAMI ULLAH',
            'fatherName' => ' ',
            'CNIC' => '36300-0000000-16',
            'Roll_No' => 'CPE-23-17',
            'Reg_No' => '16',
            'Session' =>  '2023-2027',
            
            'Admission_Challan_Draft' => Null,
            'Admission_Challan_Paid' => Null,
            'Semester_1_Draft' => Null,
            'Semester_1_Paid' => Null,
            'Semester_2_Draft' => Null,
            'Semester_2_Paid' => Null,
            'Semester_3_Draft' => Null,
            'Semester_3_Paid' => Null,
            'Semester_4_Draft' => Null,
            'Semester_4_Paid' => Null,
            'Semester_5_Draft' => Null,
            'Semester_5_Paid' => Null,
            'Semester_6_Draft' => Null,
            'Semester_6_Paid' => Null,
            'Semester_7_Draft' => Null,
            'Semester_7_Paid' => Null,
            'Semester_8_Draft' => Null,
            'Semester_8_Paid' => Null,
        ]);

        FeeChallan::create([
            'id' => 17,
            'Name' => 'HAFIZ MUHAMMAD ZARYAB',
            'fatherName' => ' ',
            'CNIC' => '36300-0000000-17',
            'Roll_No' => 'CPE-23-18',
            'Reg_No' => '17',
            'Session' =>  '2023-2027',
            
      
            'Admission_Challan_Draft' => Null,
            'Admission_Challan_Paid' => Null,
            'Semester_1_Draft' => Null,
            'Semester_1_Paid' => Null,
            'Semester_2_Draft' => Null,
            'Semester_2_Paid' => Null,
            'Semester_3_Draft' => Null,
            'Semester_3_Paid' => Null,
            'Semester_4_Draft' => Null,
            'Semester_4_Paid' => Null,
            'Semester_5_Draft' => Null,
            'Semester_5_Paid' => Null,
            'Semester_6_Draft' => Null,
            'Semester_6_Paid' => Null,
            'Semester_7_Draft' => Null,
            'Semester_7_Paid' => Null,
            'Semester_8_Draft' => Null,
            'Semester_8_Paid' => Null,
        ]);

        FeeChallan::create([
            'id' => 18,
            'Name' => 'MUHAMMAD REHAN',
            'fatherName' => ' ',
            'CNIC' => '36300-0000000-18',
            'Roll_No' => 'CPE-23-19',
            'Reg_No' => '18',
            'Session' =>  '2023-2027',
            
            'Admission_Challan_Draft' => Null,
            'Admission_Challan_Paid' => Null,
            'Semester_1_Draft' => Null,
            'Semester_1_Paid' => Null,
            'Semester_2_Draft' => Null,
            'Semester_2_Paid' => Null,
            'Semester_3_Draft' => Null,
            'Semester_3_Paid' => Null,
            'Semester_4_Draft' => Null,
            'Semester_4_Paid' => Null,
            'Semester_5_Draft' => Null,
            'Semester_5_Paid' => Null,
            'Semester_6_Draft' => Null,
            'Semester_6_Paid' => Null,
            'Semester_7_Draft' => Null,
            'Semester_7_Paid' => Null,
            'Semester_8_Draft' => Null,
            'Semester_8_Paid' => Null,
        ]);

        FeeChallan::create([
            'id' => 19,
            'Name' => 'ANAM BIBI',
            'fatherName' => ' ',
            'CNIC' => '36300-0000000-19',
            'Roll_No' => 'CPE-23-20',
            'Reg_No' => '19',
            'Session' =>  '2023-2027',
           
            'Admission_Challan_Draft' => Null,
            'Admission_Challan_Paid' => Null,
            'Semester_1_Draft' => Null,
            'Semester_1_Paid' => Null,
            'Semester_2_Draft' => Null,
            'Semester_2_Paid' => Null,
            'Semester_3_Draft' => Null,
            'Semester_3_Paid' => Null,
            'Semester_4_Draft' => Null,
            'Semester_4_Paid' => Null,
            'Semester_5_Draft' => Null,
            'Semester_5_Paid' => Null,
            'Semester_6_Draft' => Null,
            'Semester_6_Paid' => Null,
            'Semester_7_Draft' => Null,
            'Semester_7_Paid' => Null,
            'Semester_8_Draft' => Null,
            'Semester_8_Paid' => Null,
        ]);

        FeeChallan::create([
            'id' => 20,
            'Name' => 'ESHA ASLAM',
            'fatherName' => ' ',
            'CNIC' => '36300-0000000-20',
            'Roll_No' => 'CPE-23-21',
            'Reg_No' => '20',
            'Session' =>  '2023-2027',
           
            'Admission_Challan_Draft' => Null,
            'Admission_Challan_Paid' => Null,
            'Semester_1_Draft' => Null,
            'Semester_1_Paid' => Null,
            'Semester_2_Draft' => Null,
            'Semester_2_Paid' => Null,
            'Semester_3_Draft' => Null,
            'Semester_3_Paid' => Null,
            'Semester_4_Draft' => Null,
            'Semester_4_Paid' => Null,
            'Semester_5_Draft' => Null,
            'Semester_5_Paid' => Null,
            'Semester_6_Draft' => Null,
            'Semester_6_Paid' => Null,
            'Semester_7_Draft' => Null,
            'Semester_7_Paid' => Null,
            'Semester_8_Draft' => Null,
            'Semester_8_Paid' => Null,
        ]);

        FeeChallan::create([
            'id' => 21,
            'Name' => 'AWAIS ALI',
            'fatherName' => ' ',
            'CNIC' => '36300-0000000-21',
            'Roll_No' => 'CPE-23-22',
            'Reg_No' => '21',
            'Session' =>  '2023-2027',
           
            'Admission_Challan_Draft' => Null,
            'Admission_Challan_Paid' => Null,
            'Semester_1_Draft' => Null,
            'Semester_1_Paid' => Null,
            'Semester_2_Draft' => Null,
            'Semester_2_Paid' => Null,
            'Semester_3_Draft' => Null,
            'Semester_3_Paid' => Null,
            'Semester_4_Draft' => Null,
            'Semester_4_Paid' => Null,
            'Semester_5_Draft' => Null,
            'Semester_5_Paid' => Null,
            'Semester_6_Draft' => Null,
            'Semester_6_Paid' => Null,
            'Semester_7_Draft' => Null,
            'Semester_7_Paid' => Null,
            'Semester_8_Draft' => Null,
            'Semester_8_Paid' => Null,
        ]);

        FeeChallan::create([
            'id' => 22,
            'Name' => 'MUHAMMAD SHOAIB',
            'fatherName' => ' ',
            'CNIC' => '36300-0000000-22',
            'Roll_No' => 'CPE-23-23',
            'Reg_No' => '22',
            'Session' =>  '2023-2027',
            
            'Admission_Challan_Draft' => Null,
            'Admission_Challan_Paid' => Null,
            'Semester_1_Draft' => Null,
            'Semester_1_Paid' => Null,
            'Semester_2_Draft' => Null,
            'Semester_2_Paid' => Null,
            'Semester_3_Draft' => Null,
            'Semester_3_Paid' => Null,
            'Semester_4_Draft' => Null,
            'Semester_4_Paid' => Null,
            'Semester_5_Draft' => Null,
            'Semester_5_Paid' => Null,
            'Semester_6_Draft' => Null,
            'Semester_6_Paid' => Null,
            'Semester_7_Draft' => Null,
            'Semester_7_Paid' => Null,
            'Semester_8_Draft' => Null,
            'Semester_8_Paid' => Null,
        ]);
        FeeChallan::create([
            'id' => 23,
            'Name' => 'NIDA KANWAL',
            'fatherName' => ' ',
            'CNIC' => '36300-0000000-23',
            'Roll_No' => 'CPE-23-24',
            'Reg_No' => '23',
            'Session' =>  '2023-2027',
            
            'Admission_Challan_Draft' => Null,
            'Admission_Challan_Paid' => Null,
            'Semester_1_Draft' => Null,
            'Semester_1_Paid' => Null,
            'Semester_2_Draft' => Null,
            'Semester_2_Paid' => Null,
            'Semester_3_Draft' => Null,
            'Semester_3_Paid' => Null,
            'Semester_4_Draft' => Null,
            'Semester_4_Paid' => Null,
            'Semester_5_Draft' => Null,
            'Semester_5_Paid' => Null,
            'Semester_6_Draft' => Null,
            'Semester_6_Paid' => Null,
            'Semester_7_Draft' => Null,
            'Semester_7_Paid' => Null,
            'Semester_8_Draft' => Null,
            'Semester_8_Paid' => Null,
        ]);

        FeeChallan::create([
            'id' => 24,
            'Name' => 'MUHAMMAD NOUMAN',
            'fatherName' => ' ',
            'CNIC' => '36300-0000000-24',
            'Roll_No' => 'CPE-23-25',
            'Reg_No' => '24',
            'Session' =>  '2023-2027',
             
           
            'Admission_Challan_Draft' => Null,
            'Admission_Challan_Paid' => Null,
            'Semester_1_Draft' => Null,
            'Semester_1_Paid' => Null,
            'Semester_2_Draft' => Null,
            'Semester_2_Paid' => Null,
            'Semester_3_Draft' => Null,
            'Semester_3_Paid' => Null,
            'Semester_4_Draft' => Null,
            'Semester_4_Paid' => Null,
            'Semester_5_Draft' => Null,
            'Semester_5_Paid' => Null,
            'Semester_6_Draft' => Null,
            'Semester_6_Paid' => Null,
            'Semester_7_Draft' => Null,
            'Semester_7_Paid' => Null,
            'Semester_8_Draft' => Null,
            'Semester_8_Paid' => Null,
        ]);

        FeeChallan::create([
            'id' => 25,
            'Name' => 'MUBASHIR HASSAN',
            'fatherName' => ' ',
            'CNIC' => '36300-0000000-25',
            'Roll_No' => 'CPE-23-26',
            'Reg_No' => '25',
            'Session' =>  '2023-2027',
           
            'Admission_Challan_Draft' => Null,
            'Admission_Challan_Paid' => Null,
            'Semester_1_Draft' => Null,
            'Semester_1_Paid' => Null,
            'Semester_2_Draft' => Null,
            'Semester_2_Paid' => Null,
            'Semester_3_Draft' => Null,
            'Semester_3_Paid' => Null,
            'Semester_4_Draft' => Null,
            'Semester_4_Paid' => Null,
            'Semester_5_Draft' => Null,
            'Semester_5_Paid' => Null,
            'Semester_6_Draft' => Null,
            'Semester_6_Paid' => Null,
            'Semester_7_Draft' => Null,
            'Semester_7_Paid' => Null,
            'Semester_8_Draft' => Null,
            'Semester_8_Paid' => Null,
        ]);

        FeeChallan::create([
            'id' => 26,
            'Name' => 'MUHAMMAD UMAR',
            'fatherName' => ' ',
            'CNIC' => '36300-0000000-26',
            'Roll_No' => 'CPE-23-27',
            'Reg_No' => '26',
            'Session' =>  '2023-2027',
             
            'Admission_Challan_Draft' => Null,
            'Admission_Challan_Paid' => Null,
            'Semester_1_Draft' => Null,
            'Semester_1_Paid' => Null,
            'Semester_2_Draft' => Null,
            'Semester_2_Paid' => Null,
            'Semester_3_Draft' => Null,
            'Semester_3_Paid' => Null,
            'Semester_4_Draft' => Null,
            'Semester_4_Paid' => Null,
            'Semester_5_Draft' => Null,
            'Semester_5_Paid' => Null,
            'Semester_6_Draft' => Null,
            'Semester_6_Paid' => Null,
            'Semester_7_Draft' => Null,
            'Semester_7_Paid' => Null,
            'Semester_8_Draft' => Null,
            'Semester_8_Paid' => Null,
        ]);

        FeeChallan::create([
            'id' => 27,
            'Name' => 'RIZWAN ALI',
            'fatherName' => ' ',
            'CNIC' => '36300-0000000-27',
            'Roll_No' => 'CPE-23-28',
            'Reg_No' => '27',
            'Session' =>  '2023-2027',
            
       
            'Admission_Challan_Draft' => Null,
            'Admission_Challan_Paid' => Null,
            'Semester_1_Draft' => Null,
            'Semester_1_Paid' => Null,
            'Semester_2_Draft' => Null,
            'Semester_2_Paid' => Null,
            'Semester_3_Draft' => Null,
            'Semester_3_Paid' => Null,
            'Semester_4_Draft' => Null,
            'Semester_4_Paid' => Null,
            'Semester_5_Draft' => Null,
            'Semester_5_Paid' => Null,
            'Semester_6_Draft' => Null,
            'Semester_6_Paid' => Null,
            'Semester_7_Draft' => Null,
            'Semester_7_Paid' => Null,
            'Semester_8_Draft' => Null,
            'Semester_8_Paid' => Null,
        ]);

        FeeChallan::create([
            'id' => 28,
            'Name' => 'HANIA KHAN',
            'fatherName' => ' ',
            'CNIC' => '36300-0000000-28',
            'Roll_No' => 'CPE-23-29',
            'Reg_No' => '28',
            'Session' =>  '2023-2027',
            
            'Admission_Challan_Draft' => Null,
            'Admission_Challan_Paid' => Null,
            'Semester_1_Draft' => Null,
            'Semester_1_Paid' => Null,
            'Semester_2_Draft' => Null,
            'Semester_2_Paid' => Null,
            'Semester_3_Draft' => Null,
            'Semester_3_Paid' => Null,
            'Semester_4_Draft' => Null,
            'Semester_4_Paid' => Null,
            'Semester_5_Draft' => Null,
            'Semester_5_Paid' => Null,
            'Semester_6_Draft' => Null,
            'Semester_6_Paid' => Null,
            'Semester_7_Draft' => Null,
            'Semester_7_Paid' => Null,
            'Semester_8_Draft' => Null,
            'Semester_8_Paid' => Null,
        ]);

        FeeChallan::create([
            'id' => 29,
            'Name' => 'MUHAMMAD MUJAHID',
            'fatherName' => ' ',
            'CNIC' => '36300-0000000-29',
            'Roll_No' => 'CPE-23-30',
            'Reg_No' => '29',
            'Session' =>  '2023-2027',
             
            'Admission_Challan_Draft' => Null,
            'Admission_Challan_Paid' => Null,
            'Semester_1_Draft' => Null,
            'Semester_1_Paid' => Null,
            'Semester_2_Draft' => Null,
            'Semester_2_Paid' => Null,
            'Semester_3_Draft' => Null,
            'Semester_3_Paid' => Null,
            'Semester_4_Draft' => Null,
            'Semester_4_Paid' => Null,
            'Semester_5_Draft' => Null,
            'Semester_5_Paid' => Null,
            'Semester_6_Draft' => Null,
            'Semester_6_Paid' => Null,
            'Semester_7_Draft' => Null,
            'Semester_7_Paid' => Null,
            'Semester_8_Draft' => Null,
            'Semester_8_Paid' => Null,
        ]);

        FeeChallan::create([
            'id' => 30,
            'Name' => 'HASSAN GHANI',
            'fatherName' => ' ',
            'CNIC' => '36300-0000000-30',
            'Roll_No' => 'CPE-23-31',
            'Reg_No' => '30',
            'Session' =>  '2023-2027',
           
            'Admission_Challan_Draft' => Null,
            'Admission_Challan_Paid' => Null,
            'Semester_1_Draft' => Null,
            'Semester_1_Paid' => Null,
            'Semester_2_Draft' => Null,
            'Semester_2_Paid' => Null,
            'Semester_3_Draft' => Null,
            'Semester_3_Paid' => Null,
            'Semester_4_Draft' => Null,
            'Semester_4_Paid' => Null,
            'Semester_5_Draft' => Null,
            'Semester_5_Paid' => Null,
            'Semester_6_Draft' => Null,
            'Semester_6_Paid' => Null,
            'Semester_7_Draft' => Null,
            'Semester_7_Paid' => Null,
            'Semester_8_Draft' => Null,
            'Semester_8_Paid' => Null,
        ]);

        FeeChallan::create([
            'id' => 31,
            'Name' => 'YUSRA MARYAM',
            'fatherName' => ' ',
            'CNIC' => '36300-0000000-31',
            'Roll_No' => 'CPE-23-32',
            'Reg_No' => '31',
            'Session' =>  '2023-2027',
            
            'Admission_Challan_Draft' => Null,
            'Admission_Challan_Paid' => Null,
            'Semester_1_Draft' => Null,
            'Semester_1_Paid' => Null,
            'Semester_2_Draft' => Null,
            'Semester_2_Paid' => Null,
            'Semester_3_Draft' => Null,
            'Semester_3_Paid' => Null,
            'Semester_4_Draft' => Null,
            'Semester_4_Paid' => Null,
            'Semester_5_Draft' => Null,
            'Semester_5_Paid' => Null,
            'Semester_6_Draft' => Null,
            'Semester_6_Paid' => Null,
            'Semester_7_Draft' => Null,
            'Semester_7_Paid' => Null,
            'Semester_8_Draft' => Null,
            'Semester_8_Paid' => Null,
        ]);

        FeeChallan::create([
            'id' => 32,
            'Name' => 'NOOR UL AIN FATIMA',
            'fatherName' => ' ',
            'CNIC' => '36300-0000000-32',
            'Roll_No' => 'CPE-23-33',
            'Reg_No' => '32',
            'Session' =>  '2023-2027',
             
            'Admission_Challan_Draft' => Null,
            'Admission_Challan_Paid' => Null,
            'Semester_1_Draft' => Null,
            'Semester_1_Paid' => Null,
            'Semester_2_Draft' => Null,
            'Semester_2_Paid' => Null,
            'Semester_3_Draft' => Null,
            'Semester_3_Paid' => Null,
            'Semester_4_Draft' => Null,
            'Semester_4_Paid' => Null,
            'Semester_5_Draft' => Null,
            'Semester_5_Paid' => Null,
            'Semester_6_Draft' => Null,
            'Semester_6_Paid' => Null,
            'Semester_7_Draft' => Null,
            'Semester_7_Paid' => Null,
            'Semester_8_Draft' => Null,
            'Semester_8_Paid' => Null,
        ]);

        FeeChallan::create([
            'id' => 33,
            'Name' => 'ABID ALI',
            'fatherName' => ' ',
            'CNIC' => '36300-0000000-33',
            'Roll_No' => 'CPE-23-34',
            'Reg_No' => '33',
            'Session' =>  '2023-2027',
           
            'Admission_Challan_Draft' => Null,
            'Admission_Challan_Paid' => Null,
            'Semester_1_Draft' => Null,
            'Semester_1_Paid' => Null,
            'Semester_2_Draft' => Null,
            'Semester_2_Paid' => Null,
            'Semester_3_Draft' => Null,
            'Semester_3_Paid' => Null,
            'Semester_4_Draft' => Null,
            'Semester_4_Paid' => Null,
            'Semester_5_Draft' => Null,
            'Semester_5_Paid' => Null,
            'Semester_6_Draft' => Null,
            'Semester_6_Paid' => Null,
            'Semester_7_Draft' => Null,
            'Semester_7_Paid' => Null,
            'Semester_8_Draft' => Null,
            'Semester_8_Paid' => Null,
        ]);

        FeeChallan::create([
            'id' => 34,
            'Name' => 'RIAZ AHMAD',
            'fatherName' => ' ',
            'CNIC' => '36300-0000000-34',
            'Roll_No' => 'CPE-23-35',
            'Reg_No' => '34',
            'Session' =>  '2023-2027',
              
            'Admission_Challan_Draft' => Null,
            'Admission_Challan_Paid' => Null,
            'Semester_1_Draft' => Null,
            'Semester_1_Paid' => Null,
            'Semester_2_Draft' => Null,
            'Semester_2_Paid' => Null,
            'Semester_3_Draft' => Null,
            'Semester_3_Paid' => Null,
            'Semester_4_Draft' => Null,
            'Semester_4_Paid' => Null,
            'Semester_5_Draft' => Null,
            'Semester_5_Paid' => Null,
            'Semester_6_Draft' => Null,
            'Semester_6_Paid' => Null,
            'Semester_7_Draft' => Null,
            'Semester_7_Paid' => Null,
            'Semester_8_Draft' => Null,
            'Semester_8_Paid' => Null,
        ]);

        FeeChallan::create([
            'id' => 35,
            'Name' => 'MUHAMMAD AWAIS',
            'fatherName' => ' ',
            'CNIC' => '36300-0000000-35',
            'Roll_No' => 'CPE-23-36',
            'Reg_No' => '35',
            'Session' =>  '2023-2027',
             
            'Admission_Challan_Draft' => Null,
            'Admission_Challan_Paid' => Null,
            'Semester_1_Draft' => Null,
            'Semester_1_Paid' => Null,
            'Semester_2_Draft' => Null,
            'Semester_2_Paid' => Null,
            'Semester_3_Draft' => Null,
            'Semester_3_Paid' => Null,
            'Semester_4_Draft' => Null,
            'Semester_4_Paid' => Null,
            'Semester_5_Draft' => Null,
            'Semester_5_Paid' => Null,
            'Semester_6_Draft' => Null,
            'Semester_6_Paid' => Null,
            'Semester_7_Draft' => Null,
            'Semester_7_Paid' => Null,
            'Semester_8_Draft' => Null,
            'Semester_8_Paid' => Null,
        ]);

        FeeChallan::create([
            'id' => 36,
            'Name' => 'SAIFULLAH',
            'fatherName' => ' ',
            'CNIC' => '36300-0000000-36',
            'Roll_No' => 'CPE-23-37',
            'Reg_No' => '36',
            'Session' =>  '2023-2027',
             
            'Admission_Challan_Draft' => Null,
            'Admission_Challan_Paid' => Null,
            'Semester_1_Draft' => Null,
            'Semester_1_Paid' => Null,
            'Semester_2_Draft' => Null,
            'Semester_2_Paid' => Null,
            'Semester_3_Draft' => Null,
            'Semester_3_Paid' => Null,
            'Semester_4_Draft' => Null,
            'Semester_4_Paid' => Null,
            'Semester_5_Draft' => Null,
            'Semester_5_Paid' => Null,
            'Semester_6_Draft' => Null,
            'Semester_6_Paid' => Null,
            'Semester_7_Draft' => Null,
            'Semester_7_Paid' => Null,
            'Semester_8_Draft' => Null,
            'Semester_8_Paid' => Null,
        ]);

        FeeChallan::create([
            'id' => 37,
            'Name' => 'ALISHBA ARIF',
            'fatherName' => ' ',
            'CNIC' => '36300-0000000-37',
            'Roll_No' => 'CPE-23-38',
            'Reg_No' => '37',
            'Session' =>  '2023-2027',
            
            'Admission_Challan_Draft' => Null,
            'Admission_Challan_Paid' => Null,
            'Semester_1_Draft' => Null,
            'Semester_1_Paid' => Null,
            'Semester_2_Draft' => Null,
            'Semester_2_Paid' => Null,
            'Semester_3_Draft' => Null,
            'Semester_3_Paid' => Null,
            'Semester_4_Draft' => Null,
            'Semester_4_Paid' => Null,
            'Semester_5_Draft' => Null,
            'Semester_5_Paid' => Null,
            'Semester_6_Draft' => Null,
            'Semester_6_Paid' => Null,
            'Semester_7_Draft' => Null,
            'Semester_7_Paid' => Null,
            'Semester_8_Draft' => Null,
            'Semester_8_Paid' => Null,
        ]);



    }
}
